package com.hrms.practice;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.junit.Test;

public class JDBC_Demo {
	
	
	String dbUsername="syntax_hrm";
	String dbPassword="syntaxhrm123";
//	jdbc:java database connectivity
//jdbc:drivertype(mysql)://hostname(get it from sql):port/db name 
	String dbUrl="jdbc:mysql://166.62.36.207:3306/syntaxhrm_mysql";
	@Test
	public void abc() throws SQLException {
//		1)make a connection 
		Connection conn= DriverManager.getConnection(dbUrl, dbUsername, dbPassword);
		System.out.println("DB connection is successful");
		//2.retrieve statement ;Creates a Statement type object for sending SQL statements to the database. 
		Statement st=conn.createStatement();
		//3.Executes the given SQL statement, which returns a single ResultSet object.
		ResultSet rs =st.executeQuery("select * from hs_hr_employees");
		/*A table of data representing a database result set, which
 * is usually generated by executing a statement that queries the database
 */
		rs.next();
		String firstname=rs.getString("emp_firstname");
		System.out.println(firstname);
		rs.next();
		String firstname2=rs.getObject("emp_firstname").toString() ;
		System.out.println(firstname2);
		
		while (rs.next()) {
			String columnData = rs.getString("emp_firstname");
			String columnData1 = rs.getString("emp_lastname");
			System.out.println(columnData + "\t\t"+ columnData1);
		}
//		rs.close();//close resultset
//	st.close();   //close statement
//		conn.close();//close connection
////		retrieve the all job titles and store them in arraylist and show it in console
		
		while (rs.next()) {
			String columnData = rs.getString("emp_firstname");
			
		}
		
		
	}

}
